apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-chat-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-chat-demo
  template:
    metadata:
      labels:
        app: openai-chat-demo
    spec:
      containers:
        - name: openai-chat-demo
          # replaced in the github workflow with learninggithubactions.azurecr.io/openai-chat-demo:${{ github.sha }}
          image: learninggithubactions.azurecr.io/openai-chat-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: openai-chat-demo-configmap
                  key: openai-api-key
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
