name: Build and Deploy Snapshot

on:
  push:
    branches:
      - master

env:
  RESOURCE_GROUP: learning-github-actions
  AZURE_CONTAINER_REGISTRY: learninggithubactions.azurecr.io
  IMAGE_NAME: openai-chat-demo
  CLUSTER_NAME: your-aks-cluster
  NAMESPACE: default

jobs:
  build-and-deploy-snapshot:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Native Image
        run: |
          cd openai-chat-demo
          mvn -Pnative spring-boot:build-image
      # Using Service principal
      # https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=userlevel%2Caspnetcore#configure-the-github-secret
      # https://github.com/marketplace/actions/azure-login
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure CLI command
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
             az account show