name: Build and Deploy Snapshot

on:
  push:
    branches:
      - master

env:
  RESOURCE_GROUP: learning-github-actions
  AZURE_CONTAINER_REGISTRY: learninggithubactions.azurecr.io
  IMAGE_NAME: openai-chat-demo
  AKS_CLUSTER_NAME: learning-github-actions
  KUSTOMIZE_PATH: ./k8s/overlays/dev

jobs:
  build-and-deploy-snapshot:
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Native Image
        run: |
          cd openai-chat-demo
          mvn -Pnative spring-boot:build-image
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Docker tag and push image
        run: |
          docker tag docker.io/library/$IMAGE_NAME:0.0.1-SNAPSHOT ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      - name: Write secret to file
        run: echo "openai-api-key=${{ secrets.OPENAI_API_KEY }}" > k8s/base/${{ env.IMAGE_NAME}}-secret.txt
      - name: Bake manifests with Kustomize
        uses: azure/k8s-bake@v3
        id: bake
        with:
          renderEngine: kustomize
          kustomizationPath: ${{ env.KUSTOMIZE_PATH }}
          kubectl-version: latest
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v5
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}